### ISSUE TITLE
Module exports a default property, typescript compiler config issue ?

### ISSUE THREAD

**Issue by Nowadays** [svsool/axios-better-stacktrace#2]
Hi,

When importing this module in a node ESM environment the function exported is exported as `default`, which is not what you intended, cf: the readme.

![image](https://user-images.githubusercontent.com/4912348/109622584-8dab4c80-7b3c-11eb-941a-a2c38576ef53.png)

**Comment by svsool** [comment]
Hi,

Sorry for confusion. So far, this plugin is compiled to CommonJS and implies `esModuleInterop` to handle ES imports like in readme. CommonJS example though uses `require` + `default` combination.

Maybe I can take a look at some point to make it nicer for ESM envs by adding a separate TS build, so it could be imported directly as `import axiosBetterStacktrace from ...` instead of `import { default as axiosBetterStacktrace } from ...` without `esModuleInterop` enabled.

**Comment by Nowadays** [comment]
Thank you for the quick reply, and thank you for this lib as it's a time saver when dealing with axios error.

Closing the issue since it's not a deal breaker.
